# Generated by Django 5.1.5 on 2025-01-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_portal_app', '0001_initial'),
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='users.location'),
        ),
    ]
