# Generated by Django 5.1.5 on 2025-01-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_portal_app', '0005_servicerequest_accepted_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
